---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/content/pages
  label: Puslapiai
  create: all
  match: "**/*"
  templates:
  - puslapis
- type: heading
  label: Parama
- type: directory
  path: src/content/organizacijos-aukojimui
  label: Aukojimas
  create: documents
  match: "**/*"
  templates:
  - organizacija
- type: directory
  path: src/content/organizacijos-savanorystei
  label: Savanorystė
  create: documents
  match: "**/*"
  templates:
  - organizacija-savanorystei
- type: heading
  label: Protestas
- type: directory
  path: src/content/events
  label: Renginiai
  create: documents
  match: "**/*"
  templates:
  - renginys
- type: directory
  path: src/content/initiatives
  label: Akcijos
  create: documents
  match: "**/*"
  templates:
  - akcija
- type: directory
  path: src/content/addressees
  label: Laiškų rašymas
  create: documents
  match: "**/*"
  templates:
  - adresatas-laiskams
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
