on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:adaptdk/su-ukraina.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:adaptdk/su-ukraina_storybook.git"
          destination_branch: "refs/heads/*"
